apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-deployment
  namespace: sock-shop
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: curlpod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: curlpod
    spec:
      containers:
      - command:
        - sh
        - -c
        - while true; do sleep 1; done
        image: radial/busyboxplus:curl
        imagePullPolicy: IfNotPresent
        name: curlpod
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: secret-volume
        secret:
          defaultMode: 420
          secretName: nginxsecret
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-07-25T15:54:22Z"
    lastUpdateTime: "2022-07-25T15:54:22Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-07-25T15:54:17Z"
    lastUpdateTime: "2022-07-25T15:54:22Z"
    message: ReplicaSet "curl-deployment-77547c64d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
