apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyk-gtw
  labels:
    app: tyk-gtw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tyk-gtw
  template:
    metadata:
      labels:
        app: tyk-gtw
    spec:
      containers:
        - name: tyk-gtw
          image: "tykio/tyk-gateway:v3.2.2"
          imagePullPolicy: Always
          ports:
            - containerPort: 8089
          env:
            - name: TYK_GW_LISTENPORT
              value: "8080"
            - name: TYK_GW_SECRET
              value: "foo"
            - name: TYK_GW_STORAGE_HOST
              value: "redis"
            - name: TYK_GW_STORAGE_PORT
              value: "6379"
            - name: TYK_GW_STORAGE_PASSWORD
              value: ""
            - name: TYK_LOGLEVEL
              value: "info"
            - name: GODEBUG
              value: "netdns=cgo"
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          volumeMounts:
            - name: tyk-gateway-conf
              mountPath: /opt/tyk-gateway/tyk.conf
              subPath: tyk.conf
            - name: tyk-apidefs
              subPath: httpbin.json
              mountPath: /opt/tyk-gateway/apps/httpbin.json
            - name: tyk-apidefs
              subPath: jsonplaceholder.json
              mountPath: /opt/tyk-gateway/apps/jsonplaceholder.json
      volumes:
        - name: tyk-apidefs
          configMap:
            name: tyk-apidefs
            items:
              - key: httpbin.json
                path: httpbin.json
              - key: jsonplaceholder.json
                path: jsonplaceholder.json
        - name: tyk-gateway-conf
          configMap:
            name: tyk-gateway-conf
            items:
              - key: tyk.conf
                path: tyk.conf
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: tyk-svc
  namespace: tyk
  labels:
    app: tyk-gtw
spec:
  ports:
    - name: proxy
      port: 80
      targetPort: 8080
  selector:
    app: tyk-gtw
  type: LoadBalancer

