args: !!python/object:argparse.Namespace
  b1: 0.5
  b2: 0.5
  batch_size: 128
  data_dir: ../Data/
  epochs: 80
  log_dir: VAE_logs
  lr: 0.001
  num_filters: 20
  num_workers: 4
  progress_bar: false
  seed: 42
  z_dim: 10
num_filters: 20
z_dim: 10
